services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama14
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  ollama-data:
